addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.2.0")
addSbtPlugin("nl.gn0s1s" % "sbt-dotenv" % "3.0.0")
addSbtPlugin("org.jetbrains.scala" % "sbt-kotlin-plugin" % "3.1.4")
//addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.24.0")
//addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")